services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: sequence-game-backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: '${SPRING_DATASOURCE_URL}'
      CORS_ALLOWED_ORIGINS: '${CORS_ALLOWED_ORIGINS}'

